# Generated by Django 4.1.2 on 2022-10-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figour', '0007_alter_fpfigours_mojood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpfigours',
            name='mojood',
            field=models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی'),
        ),
    ]
