# Generated by Django 4.1.2 on 2022-10-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figour', '0008_alter_fpfigours_mojood'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpfigours',
            name='description',
            field=models.CharField(default=2, max_length=1000, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fpfigours',
            name='mojood',
            field=models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی'),
        ),
    ]
