# Generated by Django 4.1.2 on 2022-11-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figour', '0018_alter_fpfigours_mojood_alter_fpporforoosh_mojood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpfigours',
            name='mojood',
            field=models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='fpporforoosh',
            name='mojood',
            field=models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی'),
        ),
    ]
