# Generated by Django 4.1.2 on 2022-10-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figour', '0005_alter_fpfigours_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpfigours',
            name='mojood',
            field=models.CharField(choices=[('N', 'ناموجود'), ('M', 'موجود')], default='M', max_length=10, verbose_name='موجودی'),
        ),
    ]
