# Generated by Django 4.1.2 on 2022-10-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figour', '0009_fpfigours_description_alter_fpfigours_mojood'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpfigours',
            name='arzesh',
            field=models.IntegerField(default=100, verbose_name='ارزش خرید'),
        ),
        migrations.AddField(
            model_name='fpfigours',
            name='keifiat',
            field=models.IntegerField(default=100, verbose_name='کیفیت ساخت'),
        ),
        migrations.AddField(
            model_name='fpfigours',
            name='sohoolat',
            field=models.IntegerField(default=100, verbose_name='سهولت استفاده'),
        ),
        migrations.AlterField(
            model_name='fpfigours',
            name='mojood',
            field=models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی'),
        ),
    ]
