# Generated by Django 4.1.2 on 2022-11-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('figour', '0010_fpfigours_arzesh_fpfigours_keifiat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpfigours',
            name='Discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='fpfigours',
            name='mojood',
            field=models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='fpfigours',
            name='second_price',
            field=models.IntegerField(default=models.IntegerField()),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=255)),
                ('massage', models.TextField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('figour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='figour.fpfigours', verbose_name='محصول')),
            ],
        ),
    ]
