# Generated by Django 4.1.2 on 2022-11-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figour', '0011_alter_fpfigours_discount_alter_fpfigours_mojood_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='figours',
        ),
    ]
