# Generated by Django 4.1.2 on 2022-11-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figour', '0013_alter_fpfigours_mojood'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lorem1', models.TextField(verbose_name='متن اول')),
                ('lorem2', models.TextField(verbose_name='متن دوم')),
                ('lorem3', models.TextField(verbose_name='متن سوم')),
                ('lorem4', models.TextField(verbose_name='متن چهارم')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
