# Generated by Django 4.1.2 on 2022-11-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eightLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='FifthLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='firstLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='SecondLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='seventhLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='SixthLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('ناموجود است', 'ناموجود'), ('موجود است', 'موجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
    ]
