# Generated by Django 4.1.2 on 2022-11-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figourlist', '0002_fourthline'),
    ]

    operations = [
        migrations.CreateModel(
            name='afirstLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='bSecondLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='cThirdLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='dfourthline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='eFifthLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='fSixthLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='gseventhLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='heightLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField(default=models.IntegerField())),
                ('Discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='images/')),
                ('mojood', models.CharField(choices=[('موجود است', 'موجود'), ('ناموجود است', 'ناموجود')], default='موجود است', max_length=20, verbose_name='موجودی')),
                ('keifiat', models.IntegerField(default=100, verbose_name='کیفیت ساخت')),
                ('arzesh', models.IntegerField(default=100, verbose_name='ارزش خرید')),
                ('sohoolat', models.IntegerField(default=100, verbose_name='سهولت استفاده')),
            ],
        ),
        migrations.DeleteModel(
            name='eightLine',
        ),
        migrations.DeleteModel(
            name='FifthLine',
        ),
        migrations.DeleteModel(
            name='firstLine',
        ),
        migrations.DeleteModel(
            name='fourthline',
        ),
        migrations.DeleteModel(
            name='SecondLine',
        ),
        migrations.DeleteModel(
            name='seventhLine',
        ),
        migrations.DeleteModel(
            name='SixthLine',
        ),
        migrations.DeleteModel(
            name='ThirdLine',
        ),
    ]
